Repository Henrixounez/PixWorld-Frontend, pull requests merged in 2021-08, with the labels that each got.

#20 [ADD]: i18n FR/EN
  next-i18next.config.js
  next.config.js
  package-lock.json
  package.json
  pages/_app.page.tsx
  pages/constants/languages.ts
  pages/controller/ConnectionController.ts
  pages/index.page.tsx
  pages/ui/Chat.tsx
  pages/ui/Cooldown.tsx
  pages/ui/Overlay.tsx
  pages/ui/modals/Captcha.tsx
  pages/ui/modals/Converter.tsx
  pages/ui/modals/Infos.tsx
  pages/ui/modals/Parameters.tsx
  public/locales/en/captcha.json
  public/locales/en/common.json
  public/locales/en/converter.json
  public/locales/en/infos.json
  public/locales/en/overlay.json
  public/locales/en/parameters.json
  public/locales/fr/captcha.json
  public/locales/fr/common.json
  public/locales/fr/converter.json
  public/locales/fr/infos.json
  public/locales/fr/overlay.json
  public/locales/fr/parameters.json
Labels: enhancement

#21 [ADD]: Calculate cooldown as diff of Date
  pages/ui/Cooldown.tsx
Labels: enhancement

#23 [FIX]: Captcha on mobile
  pages/ui/modals/Captcha.tsx
Labels: bug

#26 [FIX]: Light blue inside hover square outside of the map
  pages/controller/CanvasController.ts
  pages/controller/InteractionController.ts
Labels: bug

#30 [ADD]: User Auth + Stats
  pages/constants/modalTypes.ts
  pages/controller/ConnectionController.ts
  pages/index.page.tsx
  pages/ui/ButtonList.tsx
  pages/ui/Modal.tsx
  pages/ui/PlayerCounter.tsx
  pages/ui/modals/Login.tsx
  pages/ui/modals/Register.tsx
  pages/ui/modals/Stats.tsx
  store/actions/user.ts
  store/index.ts
  store/reducer.ts
Labels: enhancement

#33 [ADD]: Pixel Activity + Activity Parameter
  pages/controller/CanvasController.ts
  pages/controller/ConnectionController.ts
  pages/ui/modals/Parameters.tsx
  public/locales/en/parameters.json
  public/locales/fr/parameters.json
  public/locales/ptbr/parameters.json
  store/actions/parameters.ts
  store/index.ts
Labels: enhancement

#36 [FIX]: Autofocus canvas on page load & after captcha
  pages/controller/CanvasController.ts
  pages/ui/modals/Captcha.tsx
Labels: enhancement

#37 [FIX]: Stop Long Touch from selecting text + no select color when zooming/moving
  pages/controller/InteractionController.ts
Labels: enhancement

#39 [FIX]: Placing pixels on mobile
  pages/controller/InteractionController.ts
Labels: bug

#40 [ADD]: Pixel rankings
  pages/constants/languages.ts
  pages/controller/ConnectionController.ts
  pages/ui/Modal.tsx
  pages/ui/modals/Converter.tsx
  pages/ui/modals/Infos.tsx
  pages/ui/modals/Parameters.tsx
  pages/ui/modals/Problem.tsx
  pages/ui/modals/Stats.tsx
  public/locales/en/converter.json
  public/locales/en/problem.json
  public/locales/en/stats.json
  public/locales/fr/converter.json
  public/locales/fr/problem.json
  public/locales/fr/stats.json
  public/locales/ptbr/converter.json
  store/actions/user.ts
Labels: enhancement

#42 [ADD]: Restrict chat only for logged
  pages/constants/languages.ts
  pages/controller/CanvasController.ts
  pages/ui/Chat.tsx
  public/locales/en/chat.json
  public/locales/en/common.json
  public/locales/fr/chat.json
  public/locales/fr/common.json
  store/actions/parameters.ts
  store/index.ts
Labels: enhancement

#44 [ADD]: More chat features (Positions, here, help, mentions, greentext)
  package-lock.json
  package.json
  pages/controller/CanvasController.ts
  pages/ui/Chat.tsx
  pages/ui/ChatFormatting.tsx
  store/actions/painting.ts
  store/index.ts
Labels: enhancement

#46 [ADD]: New keys to move and activate options + Alert + Rendering lifecycle rework
  pages/controller/CanvasController.ts
  pages/controller/ConnectionController.ts
  pages/controller/InteractionController.ts
  pages/controller/OverlayController.ts
  pages/index.page.tsx
  pages/ui/Alert.tsx
  pages/ui/Cooldown.tsx
  pages/ui/PaletteList.tsx
  pages/ui/modals/Parameters.tsx
  store/actions/infos.ts
  store/actions/overlay.ts
  store/actions/painting.ts
  store/actions/parameters.ts
  store/index.ts
Labels: enhancement

#48 [ADD]: Overlay options (Save, Share, Import, ...)
  pages/constants/modalTypes.ts
  pages/controller/CanvasController.ts
  pages/controller/OverlayController.ts
  pages/ui/Modal.tsx
  pages/ui/Overlay.tsx
  pages/ui/modals/Overlay.tsx
  public/locales/en/overlay.json
  public/locales/fr/overlay.json
  store/actions/overlay.ts
  store/index.ts
Labels: enhancement

#50 [ADD]: Grid option on converter
  pages/ui/modals/Converter.tsx
  public/locales/en/converter.json
  public/locales/fr/converter.json
Labels: enhancement

#52 [ADD]: Search box for grid position
  pages/controller/InteractionController.ts
  pages/ui/ButtonList.tsx
  store/actions/infos.ts
  store/index.ts
Labels: enhancement

#54 [ADD]: Notifications when pixel cooldown is finished
  pages/constants/languages.ts
  pages/controller/CanvasController.ts
  pages/ui/Cooldown.tsx
  pages/ui/modals/Parameters.tsx
  public/locales/en/notification.json
  public/locales/en/parameters.json
  public/locales/fr/notification.json
  public/locales/fr/parameters.json
  store/actions/parameters.ts
  store/index.ts
  store/reducer.ts
Labels: enhancement

#55 [ADD]: Sounds + more alerts on keys and alert translations
  pages/constants/languages.ts
  pages/controller/CanvasController.ts
  pages/controller/InteractionController.ts
  pages/controller/SoundController.ts
  pages/ui/Alert.tsx
  pages/ui/Cooldown.tsx
  pages/ui/modals/Parameters.tsx
  public/locales/en/alerts.json
  public/locales/en/parameters.json
  public/locales/fr/alerts.json
  public/locales/fr/parameters.json
  public/sounds/bad.wav
  public/sounds/good.wav
  public/sounds/neutral.wav
  public/sounds/options.wav
  store/actions/parameters.ts
  store/index.ts
Labels: enhancement

#63 [FIX]: Show no pixel activity when in history mode
  pages/controller/CanvasController.ts
Labels: bug

#65 [ADD]: Multicanvas + only one chunk img + some history fixes
  pages/controller/CanvasController.ts
  pages/controller/Chunk.ts
  pages/controller/ConnectionController.ts
  pages/ui/HistoryMode.tsx
  pages/ui/modals/Parameters.tsx
  store/actions/parameters.ts
  store/index.ts
Labels: enhancement

#69 [ADD]: Recenter when changing canvas
  pages/ui/modals/Parameters.tsx
  store/actions/parameters.ts
Labels: bug, enhancement

#71 [ADD]: Superchunks + unlock zoom + limit position
  pages/controller/CanvasController.ts
  pages/controller/Chunk.ts
  pages/controller/InteractionController.ts
  pages/index.page.tsx
Labels: enhancement

#72 [ADD]: Position tag includes canvases and zoom infos + Some render improvements
  pages/controller/CanvasController.ts
  pages/ui/ButtonList.tsx
  pages/ui/Chat.tsx
  pages/ui/ChatFormatting.tsx
  pages/ui/modals/Parameters.tsx
  store/actions/infos.ts
  store/actions/parameters.ts
Labels: enhancement

#75 [ADD]: Refresh from WS
  pages/controller/Chunk.ts
  pages/controller/ConnectionController.ts
Labels: enhancement

#77 [ADD]: Red bubble on unread messages
  pages/controller/CanvasController.ts
  pages/ui/Chat.tsx
  store/actions/chat.ts
  store/actions/parameters.ts
  store/index.ts
Labels: enhancement

#79 [FIX]: History date timezones + keep value after closing/reopening
  pages/ui/HistoryMode.tsx
Labels: bug

#80 History right shift
  pages/controller/CanvasController.ts
  pages/controller/InteractionController.ts
Labels: enhancement

#86 [ADD]: Copy URL with shift+c and cursor pos with C + copy pos on clicking cursor pos box
  pages/controller/InteractionController.ts
  pages/ui/CursorPosition.tsx
Labels: enhancement

#87 [ADD]: Hotkey list in help
  pages/ui/modals/Infos.tsx
  public/locales/en/infos.json
  public/locales/fr/infos.json
Labels: enhancement

#91 [ADD]: Bookmarks
  pages/constants/modalTypes.ts
  pages/controller/InteractionController.ts
  pages/ui/ButtonList.tsx
  pages/ui/Modal.tsx
  pages/ui/modals/Bookmarks.tsx
  store/actions/infos.ts
Labels: enhancement

#94 [ADD]: Disconnection reason for user
  pages/controller/ConnectionController.ts
  pages/ui/modals/Problem.tsx
  store/actions/infos.ts
  store/index.ts
Labels: enhancement

#95 [ADD]: Alerts user on why they cant place pixel
  pages/controller/ConnectionController.ts
  pages/ui/Alert.tsx
  pages/ui/Cooldown.tsx
Labels: enhancement

#99 [FIX]: Mobile scrolling
  pages/ui/Modal.tsx
  styles/index.css
Labels: bug

#102 [ADD]: Admin allow copy pasting of coordinates + save page with dynamic routing
  pages/admin/Logs.tsx
  pages/admin/MapOperations.tsx
  pages/admin/[page].page.tsx
  pages/admin/sidebar.tsx
  pages/admin/utils.tsx
Labels: enhancement

#103 [ADD]: Responsive admin tools + redirect /admin to /admin/activity
  next.config.js
  pages/admin/Activity.tsx
  pages/admin/Logs.tsx
  pages/admin/[page].page.tsx
  pages/admin/sidebar.tsx
  pages/admin/utils.tsx
Labels: enhancement

#107 [FIX]: Zooming
  pages/controller/CanvasController.ts
  pages/controller/InteractionController.ts
Labels: bug

#121 [ADD]: Rules in infos modal
  pages/ui/modals/Infos.tsx
  public/locales/en/infos.json
  public/locales/fr/infos.json
Labels: enhancement

#122 [ADD]: Captcha refresh button
  pages/ui/modals/Captcha.tsx
Labels: enhancement

#123 [ADD]: Simple markdown: Bold/Italics/Underline/Code
  pages/ui/ChatFormatting.tsx
Labels: enhancement

#124 [ADD]: 1:1 Zoom level on key L
  pages/controller/InteractionController.ts
  public/locales/en/infos.json
  public/locales/fr/infos.json
Labels: enhancement

#126 [ADD]: Download viewport at 1:1 in settings
  pages/ui/modals/Parameters.tsx
Labels: enhancement

#128 [ADD]: Dropdown buttons to hide/show them
  pages/ui/ButtonList.tsx
  public/locales/en/parameters.json
  public/locales/fr/parameters.json
  store/actions/parameters.ts
  store/index.ts
Labels: enhancement
